### ISSUE TITLE
Webinterface not working

### ISSUE THREAD

**Issue by m3dc85** [alsterman/wellness2tcx-cljs#4]
Hello there, 

I try to use the webinterface with the following link adding the input and the time, but i do not get the download action 

https://alsterman.github.io/wellness2tcx-cljs/

What do you think could be the problem?

Thanks in advance,

**Comment by m3dc85** [comment]
attached the import from the webinterface 
{"data":{"analitics":{"descriptor":[{"i":0,"pr":{"name":"Power","um":"Watt"}},{"i":1,"pr":{"name":"Spm","um":"Spm"}},{"i":2,"pr":{"name":"HDistance","um":"Meter"}},{"i":3,"pr":{"name":"Grade","um":"Percent"}},{"i":4,"pr":{"name":"Level","um":"Number"}}],"samples":[{"vs":[14.0,60.0,0.56,8.0,1.0],"t":1},{"vs":[14.0,60.0,0.56,8.0,1.0],"t":2},{"vs":[16.0,60.0,1.18,8.0,1.0],"t":3},{"vs":[15.0,58.0,1.74,8.0,1.0],"t":4},{"vs":[15.0,62.0,2.36,8.0,1.0],"t":5},{"vs":[16.0,64.0,2.98,8.0,1.0],"t":6},{"vs":[17.0,66.0,3.64,8.0,1.0],"t":7},{"vs":[17.0,66.0,4.3,8.0,1.0],"t":8},{"vs":[16.0,62.0,4.96,8.0,1.0],"t":9},{"vs":[18.0,70.0,5.62,8.0,1.0],"t":10},{"vs":[20.0,80.0,6.36,8.0,1.0],"t":11},{"vs":[21.0,84.0,7.16,8.0,1.0],"t":12},{"vs":[22.0,86.0,8.0,8.0,1.0],"t":13},{"vs":[22.0,86.0,8.84,8.0,1.0],"t":14},{"vs":[22.0,88.0,9.7,8.0,1.0],"t":15},{"vs":[23.0,92.0,10.58,8.0,1.0],"t":16},{"vs":[24.0,92.0,12.42,8.0,1.0],"t":17},{"vs":[24.0,92.0,12.42,8.0,1.0],"t":18},{"vs":[25.0,98.0,13.4,8.0,1.0],"t":19},{"vs":[25.0,96.0,14.36,8.0,1.0],"t":20},{"vs":[25.0,98.0,15.34,8.0,1.0],"t":21},{"vs":[25.0,96.0,16.3,8.0,1.0],"t":22},{"vs":[25.0,96.0,17.26,8.0,1.0],"t":23},{"vs":[25.0,96.0,18.22,8.0,1.0],"t":24},{"vs":[25.0,98.0,19.18,8.0,1.0],"t":25},{"vs":[25.0,98.0,20.16,8.0,1.0],"t":26},{"vs":[25.0,100.0,21.14,8.0,1.0],"t":27},{"vs":[26.0,100.0,22.14,8.0,1.0],"t":28},{"vs":[26.0,100.0,23.14,8.0,1.0],"t":29},{"vs":[26.0,98.0,24.14,8.0,1.0],"t":30},{"vs":[25.0,96.0,25.1,8.0,1.0],"t":31},{"vs":[25.0,98.0,26.08,8.0,1.0],"t":32},{"vs":[26.0,100.0,27.06,8.0,1.0],"t":33},{"vs":[26.0,100.0,28.06,8.0,1.0],"t":34},{"vs":[26.0,102.0,29.08,8.0,1.0],"t":35},{"vs":[27.0,102.0,30.1,8.0,1.0],"t":36},{"vs":[27.0,104.0,31.12,8.0,1.0],"t":37},{"vs":[27.0,102.0,32.16,8.0,1.0],"t":38},{"vs":[26.0,102.0,33.18,8.0,1.0],"t":39},{"vs":[27.0,104.0,34.2,8.0,1.0],"t":40},{"vs":[27.0,104.0,35.24,8.0,1.0],"t":41},{"vs":[28.0,108.0,36.28,8.0,1.0],"t":42},{"vs":[28.0,108.0,36.28,8.0,1.0],"t":43},{"vs":[28.0,108.0,38.44,8.0,1.0],"t":44},{"vs":[28.0,106.0,39.5,8.0,1.0],"t":45},{"vs":[27.0,106.0,40.56,8.0,1.0],"t":46},{"vs":[27.0,108.0,41.64,8.0,1.0],"t":47},{"vs":[28.0,108.0,42.72,8.0,1.0],"t":48},{"vs":[28.0,108.0,43.8,8.0,1.0],"t":49},{"vs":[28.0,108.0,44.88,8.0,1.0],"t":50},{"vs":[28.0,110.0,45.98,8.0,1.0],"t":51},{"vs":[28.0,110.0,47.08,8.0,1.0],"t":52},{"vs":[28.0,110.0,48.18,8.0,1.0],"t":53},{"vs":[29.0,112.0,49.28,8.0,1.0],"t":54},{"vs":[30.0,118.0,50.46,8.0,1.0],"t":55},{"vs":[30.0,116.0,51.62,8.0,1.0],"t":56},{"vs":[30.0,118.0,52.78,8.0,1.0],"t":57},{"vs":[30.0,118.0,53.96,8.0,1.0],"t":58},{"vs":[30.0,116.0,55.14,8.0,1.0],"t":59},{"vs":[30.0,116.0,56.3,8.0,1.0],"t":60},{"vs":[30.0,118.0,57.46,8.0,1.0],"t":61},{"vs":[30.0,116.0,58.64,8.0,1.0],"t":62},{"vs":[29.0,112.0,59.8,8.0,1.0],"t":63},{"vs":[28.0,112.0,60.92,8.0,1.0],"t":64},{"vs":[28.0,112.0,60.92,8.0,1.0],"t":65},{"vs":[29.0,112.0,63.16,8.0,1.0],"t":66},{"vs":[30.0,116.0,64.32,8.0,1.0],"t":67},{"vs":[30.0,116.0,65.48,8.0,1.0],"t":68},{"vs":[30.0,110.0,66.62,8.0,1.0],"t":69},{"vs":[28.0,110.0,67.72,8.0,1.0],"t":70},{"vs":[29.0,114.0,68.86,8.0,1.0],"t":71},{"vs":[29.0,112.0,70.0,8.0,1.0],"t":72},{"vs":[29.0,110.0,71.12,8.0,1.0],"t":73},{"vs":[28.0,108.0,72.2,8.0,1.0],"t":74},{"vs":[28.0,112.0,73.3,8.0,1.0],"t":75},{"vs":[29.0,112.0,74.42,8.0,1.0],"t":76},{"vs":[29.0,114.0,75.54,8.0,1.0],"t":77},{"vs":[30.0,116.0,76.68,8.0,1.0],"t":78},{"vs":[29.0,112.0,77.82,8.0,1.0],"t":79},{"vs":[28.0,108.0,78.9,8.0,1.0],"t":80},{"vs":[27.0,106.0,79.98,8.0,1.0],"t":81},{"vs":[28.0,110.0,81.06,8.0,1.0],"t":82},{"vs":[29.0,116.0,82.2,8.0,1.0],"t":83},{"vs":[29.0,114.0,83.36,8.0,1.0],"t":84},{"vs":[29.0,112.0,84.5,8.0,1.0],"t":85},{"vs":[28.0,112.0,85.6,8.0,1.0],"t":86},{"vs":[29.0,114.0,86.72,8.0,1.0],"t":87},{"vs":[29.0,114.0,86.72,8.0,1.0],"t":88},{"vs":[29.0,116.0,89.02,8.0,1.0],"t":89},{"vs":[30.0,116.0,90.18,8.0,1.0],"t":90},{"vs":[29.0,114.0,91.32,8.0,1.0],"t":91},{"vs":[29.0,110.0,92.42,8.0,1.0],"t":92},{"vs":[28.0,110.0,93.52,8.0,1.0],"t":93},{"vs":[28.0,112.0,94.64,8.0,1.0],"t":94},{"vs":[29.0,116.0,95.8,8.0,1.0],"t":95},{"vs":[30.0,112.0,96.94,8.0,1.0],"t":96},{"vs":[29.0,110.0,98.04,8.0,1.0],"t":97},{"vs":[28.0,112.0,99.16,8.0,1.0],"t":98},{"vs":[29.0,114.0,100.3,8.0,1.0],"t":99},{"vs":[29.0,114.0,101.44,8.0,1.0],"t":100},{"vs":[29.0,114.0,102.58,8.0,1.0],"t":101},{"vs":[29.0,114.0,103.72,8.0,1.0],"t":102},{"vs":[29.0,114.0,104.86,8.0,1.0],"t":103},{"vs":[29.0,112.0,105.98,8.0,1.0],"t":104},{"vs":[28.0,112.0,107.1,8.0,1.0],"t":105},{"vs":[29.0,114.0,108.22,8.0,1.0],"t":106},{"vs":[29.0,114.0,108.22,8.0,1.0],"t":107},{"vs":[29.0,112.0,110.48,8.0,1.0],"t":108},{"vs":[29.0,114.0,111.62,8.0,1.0],"t":109},{"vs":[29.0,112.0,112.74,8.0,1.0],"t":110},{"vs":[29.0,112.0,113.86,8.0,1.0],"t":111},{"vs":[29.0,114.0,115.0,8.0,1.0],"t":112},{"vs":[29.0,112.0,116.12,8.0,1.0],"t":113},{"vs":[29.0,112.0,117.24,8.0,1.0],"t":114},{"vs":[29.0,112.0,118.36,8.0,1.0],"t":115},{"vs":[29.0,112.0,119.48,8.0,1.0],"t":116},{"vs":[29.0,116.0,120.6,8.0,1.0],"t":117},{"vs":[30.0,118.0,121.76,8.0,1.0],"t":118},{"vs":[30.0,116.0,122.92,8.0,1.0],"t":119},{"vs":[30.0,116.0,124.08,8.0,1.0],"t":120},{"vs":[29.0,114.0,125.24,8.0,1.0],"t":121},{"vs":[29.0,112.0,126.36,8.0,1.0],"t":122},{"vs":[29.0,114.0,127.48,8.0,1.0],"t":123},{"vs":[30.0,118.0,128.62,8.0,1.0],"t":124},{"vs":[30.0,120.0,129.8,8.0,1.0],"t":125},{"vs":[30.0,120.0,129.8,8.0,1.0],"t":126},{"vs":[31.0,122.0,131.0,8.0,1.0],"t":127},{"vs":[31.0,120.0,133.42,8.0,1.0],"t":128},{"vs":[31.0,122.0,134.64,8.0,1.0],"t":129},{"vs":[31.0,124.0,135.88,8.0,1.0],"t":130},{"vs":[32.0,126.0,137.14,8.0,1.0],"t":131},{"vs":[32.0,128.0,138.42,8.0,1.0],"t":132},{"vs":[33.0,126.0,139.7,8.0,1.0],"t":133},{"vs":[32.0,128.0,140.98,8.0,1.0],"t":134},{"vs":[33.0,128.0,142.26,8.0,1.0],"t":135},{"vs":[33.0,128.0,143.54,8.0,1.0],"t":136},{"vs":[33.0,126.0,144.82,8.0,1.0],"t":137},{"vs":[32.0,126.0,146.08,8.0,1.0],"t":138},{"vs":[34.0,130.0,147.36,8.0,1.0],"t":139},{"vs":[33.0,128.0,148.64,8.0,1.0],"t":140},{"vs":[32.0,124.0,149.92,8.0,1.0],"t":141},{"vs":[31.0,122.0,151.16,8.0,1.0],"t":142},{"vs":[31.0,124.0,152.38,8.0,1.0],"t":143},{"vs":[31.0,124.0,152.38,8.0,1.0],"t":144},{"vs":[32.0,124.0,153.62,8.0,1.0],"t":145},{"vs":[31.0,122.0,154.86,8.0,1.0],"t":146},{"vs":[32.0,126.0,156.1,8.0,1.0],"t":147},{"vs":[32.0,126.0,157.36,8.0,1.0],"t":148},{"vs":[33.0,130.0,159.92,8.0,1.0],"t":149},{"vs":[34.0,128.0,161.2,8.0,1.0],"t":150},{"vs":[33.0,130.0,162.5,8.0,1.0],"t":151},{"vs":[33.0,126.0,163.78,8.0,1.0],"t":152},{"vs":[32.0,126.0,165.04,8.0,1.0],"t":153},{"vs":[32.0,126.0,166.3,8.0,1.0],"t":154},{"vs":[32.0,122.0,167.54,8.0,1.0],"t":155},{"vs":[31.0,126.0,168.78,8.0,1.0],"t":156},{"vs":[32.0,124.0,170.02,8.0,1.0],"t":157},{"vs":[32.0,124.0,171.26,8.0,1.0],"t":158},{"vs":[32.0,124.0,172.5,8.0,1.0],"t":159},{"vs":[32.0,122.0,173.72,8.0,1.0],"t":160},{"vs":[31.0,122.0,174.94,8.0,1.0],"t":161},{"vs":[31.0,120.0,176.14,8.0,1.0],"t":162},{"vs":[32.0,124.0,177.34,8.0,1.0],"t":163},{"vs":[32.0,126.0,178.58,8.0,1.0],"t":164},{"vs":[32.0,124.0,179.84,8.0,1.0],"t":165},{"vs":[33.0,128.0,181.1,8.0,1.0],"t":166},{"vs":[33.0,126.0,182.38,8.0,1.0],"t":167},{"vs":[33.0,126.0,182.38,8.0,1.0],"t":168},{"vs":[33.0,128.0,183.64,8.0,1.0],"t":169},{"vs":[33.0,126.0,186.2,8.0,1.0],"t":170},{"vs":[32.0,126.0,187.46,8.0,1.0],"t":171},{"vs":[33.0,128.0,188.74,8.0,1.0],"t":172},{"vs":[33.0,128.0,190.02,8.0,1.0],"t":173},{"vs":[33.0,126.0,191.3,8.0,1.0],"t":174},{"vs":[32.0,124.0,192.54,8.0,1.0],"t":175},{"vs":[32.0,126.0,193.78,8.0,1.0],"t":176},{"vs":[32.0,126.0,195.04,8.0,1.0],"t":177},{"vs":[32.0,126.0,196.3,8.0,1.0],"t":178},{"vs":[32.0,128.0,197.56,8.0,1.0],"t":179},{"vs":[33.0,130.0,198.84,8.0,1.0],"t":180},{"vs":[33.0,128.0,200.14,8.0,1.0],"t":181},{"vs":[33.0,128.0,201.42,8.0,1.0],"t":182},{"vs":[33.0,128.0,202.7,8.0,1.0],"t":183},{"vs":[33.0,128.0,203.98,8.0,1.0],"t":184},{"vs":[34.0,128.0,205.26,8.0,1.0],"t":185},{"vs":[33.0,128.0,206.54,8.0,1.0],"t":186},{"vs":[33.0,128.0,206.54,8.0,1.0],"t":187},{"vs":[34.0,130.0,207.82,8.0,1.0],"t":188},{"vs":[33.0,128.0,209.12,8.0,1.0],"t":189},{"vs":[34.0,130.0,210.4,8.0,1.0],"t":190},{"vs":[33.0,130.0,212.98,8.0,1.0],"t":191},{"vs":[34.0,128.0,214.26,8.0,1.0],"t":192},{"vs":[33.0,128.0,215.54,8.0,1.0],"t":193},{"vs":[33.0,128.0,216.82,8.0,1.0],"t":194},{"vs":[33.0,126.0,218.08,8.0,1.0],"t":195},{"vs":[32.0,130.0,219.38,8.0,1.0],"t":196},{"vs":[34.0,132.0,220.68,8.0,1.0],"t":197},{"vs":[34.0,132.0,222.02,8.0,1.0],"t":198},{"vs":[33.0,128.0,223.32,8.0,1.0],"t":199},{"vs":[34.0,130.0,224.6,8.0,1.0],"t":200},{"vs":[33.0,128.0,225.9,8.0,1.0],"t":201},{"vs":[34.0,130.0,227.2,8.0,1.0],"t":202},{"vs":[33.0,128.0,228.5,8.0,1.0],"t":203},{"vs":[33.0,128.0,229.78,8.0,2.0],"t":204},{"vs":[33.0,128.0,229.78,8.0,2.0],"t":205},{"vs":[46.0,128.0,231.06,8.0,2.0],"t":206},{"vs":[46.0,128.0,232.34,8.0,2.0],"t":207},{"vs":[45.0,126.0,233.62,8.0,2.0],"t":208},{"vs":[46.0,128.0,234.88,8.0,2.0],"t":209},{"vs":[46.0,128.0,237.44,8.0,6.0],"t":210},{"vs":[93.0,130.0,238.74,8.0,6.0],"t":211},{"vs":[95.0,122.0,240.02,8.0,6.0],"t":212},{"vs":[90.0,118.0,241.2,8.0,6.0],"t":213},{"vs":[87.0,118.0,242.38,8.0,6.0],"t":214},{"vs":[87.0,116.0,243.56,8.0,6.0],"t":215},{"vs":[86.0,112.0,244.7,8.0,6.0],"t":216},{"vs":[83.0,112.0,245.82,8.0,6.0],"t":217},{"vs":[83.0,110.0,246.94,8.0,6.0],"t":218},{"vs":[81.0,110.0,248.04,8.0,6.0],"t":219},{"vs":[81.0,110.0,249.14,8.0,6.0],"t":220},{"vs":[81.0,112.0,250.24,8.0,6.0],"t":221},{"vs":[83.0,110.0,251.34,8.0,6.0],"t":222},{"vs":[83.0,112.0,252.44,8.0,6.0],"t":223},{"vs":[83.0,112.0,253.56,8.0,6.0],"t":224},{"vs":[84.0,114.0,254.68,8.0,6.0],"t":225},{"vs":[84.0,114.0,255.82,8.0,6.0],"t":226},{"vs":[84.0,114.0,256.96,8.0,6.0],"t":227},{"vs":[84.0,114.0,256.96,8.0,6.0],"t":228},{"vs":[84.0,114.0,258.1,8.0,6.0],"t":229},{"vs":[84.0,114.0,259.24,8.0,6.0],"t":230},{"vs":[84.0,116.0,260.38,8.0,6.0],"t":231},{"vs":[86.0,114.0,262.68,8.0,6.0],"t":232},{"vs":[83.0,114.0,263.8,8.0,6.0],"t":233},{"vs":[84.0,114.0,264.94,8.0,6.0],"t":234},{"vs":[84.0,114.0,266.08,8.0,6.0],"t":235},{"vs":[83.0,112.0,267.2,8.0,6.0],"t":236},{"vs":[83.0,112.0,268.32,8.0,6.0],"t":237},{"vs":[83.0,114.0,269.44,8.0,6.0],"t":238},{"vs":[84.0,112.0,270.58,8.0,6.0],"t":239},{"vs":[84.0,114.0,271.7,8.0,6.0],"t":240},{"vs":[83.0,112.0,272.84,8.0,6.0],"t":241},{"vs":[84.0,114.0,273.96,8.0,6.0],"t":242},{"vs":[84.0,114.0,275.1,8.0,6.0],"t":243},{"vs":[84.0,114.0,275.1,8.0,6.0],"t":244},{"vs":[83.0,112.0,276.24,8.0,6.0],"t":245},{"vs":[83.0,112.0,277.36,8.0,6.0],"t":246},{"vs":[83.0,112.0,279.6,8.0,6.0],"t":247},{"vs":[83.0,112.0,280.72,8.0,6.0],"t":248},{"vs":[83.0,116.0,281.88,8.0,6.0],"t":249},{"vs":[87.0,116.0,283.04,8.0,6.0],"t":250},{"vs":[86.0,116.0,284.2,8.0,6.0],"t":251},{"vs":[86.0,118.0,285.36,8.0,6.0],"t":252},{"vs":[87.0,118.0,286.54,8.0,6.0],"t":253},{"vs":[87.0,118.0,287.72,8.0,6.0],"t":254},{"vs":[87.0,118.0,288.9,8.0,6.0],"t":255},{"vs":[87.0,118.0,290.08,8.0,6.0],"t":256},{"vs":[87.0,118.0,291.26,8.0,6.0],"t":257},{"vs":[87.0,118.0,292.44,8.0,16.0],"t":258},{"vs":[222.0,120.0,293.62,8.0,16.0],"t":259},{"vs":[215.0,114.0,294.82,8.0,16.0],"t":260},{"vs":[200.0,108.0,295.96,8.0,16.0],"t":261},{"vs":[200.0,108.0,295.96,8.0,16.0],"t":262},{"vs":[193.0,104.0,297.02,8.0,16.0],"t":263},{"vs":[189.0,102.0,298.06,8.0,16.0],"t":264},{"vs":[185.0,100.0,299.08,8.0,16.0],"t":265},{"vs":[185.0,100.0,300.08,8.0,16.0],"t":266},{"vs":[185.0,98.0,302.06,8.0,16.0],"t":267},{"vs":[185.0,100.0,303.06,8.0,16.0],"t":268},{"vs":[185.0,100.0,304.06,8.0,16.0],"t":269},{"vs":[182.0,98.0,305.04,8.0,16.0],"t":270},{"vs":[182.0,98.0,306.02,8.0,16.0],"t":271},{"vs":[189.0,102.0,307.04,8.0,16.0],"t":272},{"vs":[189.0,100.0,308.04,8.0,16.0],"t":273},{"vs":[185.0,100.0,309.04,8.0,16.0],"t":274},{"vs":[185.0,102.0,310.04,8.0,16.0],"t":275},{"vs":[189.0,100.0,311.06,8.0,16.0],"t":276},{"vs":[185.0,102.0,312.08,8.0,16.0],"t":277},{"vs":[193.0,106.0,313.12,8.0,16.0],"t":278},{"vs":[196.0,110.0,314.2,8.0,16.0],"t":279},{"vs":[204.0,106.0,315.28,8.0,16.0],"t":280},{"vs":[189.0,102.0,316.34,8.0,16.0],"t":281},{"vs":[185.0,100.0,317.36,8.0,16.0],"t":282},{"vs":[182.0,98.0,318.34,8.0,16.0],"t":283},{"vs":[182.0,98.0,319.32,8.0,16.0],"t":284},{"vs":[178.0,96.0,320.3,8.0,16.0],"t":285},{"vs":[178.0,96.0,320.3,8.0,16.0],"t":286},{"vs":[178.0,96.0,321.26,8.0,16.0],"t":287},{"vs":[174.0,96.0,322.22,8.0,16.0],"t":288},{"vs":[178.0,96.0,323.18,8.0,16.0],"t":289},{"vs":[178.0,96.0,325.1,8.0,16.0],"t":290},{"vs":[178.0,96.0,326.06,8.0,16.0],"t":291},{"vs":[182.0,98.0,327.04,8.0,16.0],"t":292},{"vs":[182.0,98.0,328.02,8.0,16.0],"t":293},{"vs":[178.0,98.0,329.0,8.0,16.0],"t":294},{"vs":[182.0,98.0,329.98,8.0,16.0],"t":295},{"vs":[182.0,98.0,330.96,8.0,16.0],"t":296},{"vs":[182.0,98.0,331.94,8.0,16.0],"t":297},{"vs":[182.0,98.0,332.92,8.0,16.0],"t":298},{"vs":[182.0,98.0,333.9,8.0,16.0],"t":299},{"vs":[182.0,98.0,334.88,8.0,16.0],"t":300},{"vs":[178.0,96.0,335.86,8.0,6.0],"t":301},{"vs":[71.0,96.0,336.82,8.0,6.0],"t":302},{"vs":[71.0,96.0,337.74,8.0,6.0],"t":303},{"vs":[75.0,102.0,338.76,8.0,6.0],"t":304},{"vs":[75.0,102.0,338.76,8.0,6.0],"t":305},{"vs":[77.0,106.0,339.78,8.0,6.0],"t":306},{"vs":[78.0,106.0,340.84,8.0,6.0],"t":307},{"vs":[80.0,108.0,341.92,8.0,6.0],"t":308},{"vs":[80.0,108.0,343.0,8.0,6.0],"t":309},{"vs":[80.0,108.0,345.16,8.0,6.0],"t":310},{"vs":[78.0,106.0,346.22,8.0,6.0],"t":311},{"vs":[78.0,106.0,347.28,8.0,6.0],"t":312},{"vs":[80.0,108.0,348.36,8.0,6.0],"t":313},{"vs":[80.0,108.0,349.44,8.0,6.0],"t":314},{"vs":[80.0,108.0,350.52,8.0,6.0],"t":315},{"vs":[80.0,108.0,351.6,8.0,6.0],"t":316},{"vs":[80.0,108.0,352.68,8.0,6.0],"t":317},{"vs":[80.0,108.0,353.76,8.0,6.0],"t":318},{"vs":[80.0,108.0,354.84,8.0,6.0],"t":319},{"vs":[80.0,108.0,355.92,8.0,6.0],"t":320},{"vs":[78.0,106.0,357.0,8.0,6.0],"t":321},{"vs":[80.0,108.0,358.06,8.0,6.0],"t":322},{"vs":[80.0,108.0,359.14,8.0,6.0],"t":323},{"vs":[80.0,108.0,360.22,8.0,6.0],"t":324},{"vs":[80.0,108.0,360.22,8.0,6.0],"t":325},{"vs":[81.0,110.0,361.3,8.0,6.0],"t":326},{"vs":[81.0,112.0,362.4,8.0,6.0],"t":327},{"vs":[83.0,112.0,363.52,8.0,6.0],"t":328},{"vs":[83.0,112.0,365.76,8.0,6.0],"t":329},{"vs":[83.0,114.0,366.9,8.0,6.0],"t":330},{"vs":[84.0,112.0,368.02,8.0,6.0],"t":331},{"vs":[83.0,112.0,369.14,8.0,6.0],"t":332},{"vs":[83.0,112.0,370.26,8.0,6.0],"t":333},{"vs":[83.0,112.0,371.38,8.0,6.0],"t":334},{"vs":[81.0,110.0,372.48,8.0,6.0],"t":335},{"vs":[81.0,112.0,373.58,8.0,6.0],"t":336},{"vs":[83.0,112.0,374.7,8.0,6.0],"t":337},{"vs":[83.0,110.0,375.82,8.0,6.0],"t":338},{"vs":[81.0,110.0,376.94,8.0,6.0],"t":339},{"vs":[81.0,110.0,378.04,8.0,6.0],"t":340},{"vs":[81.0,110.0,379.14,8.0,6.0],"t":341},{"vs":[81.0,110.0,379.14,8.0,6.0],"t":342},{"vs":[81.0,110.0,380.24,8.0,6.0],"t":343},{"vs":[81.0,110.0,381.34,8.0,5.0],"t":344},{"vs":[70.0,110.0,382.44,8.0,5.0],"t":345},{"vs":[70.0,110.0,383.54,8.0,5.0],"t":346},{"vs":[70.0,112.0,385.76,8.0,4.0],"t":347},{"vs":[62.0,112.0,386.88,8.0,3.0],"t":348},{"vs":[61.0,112.0,388.0,8.0,3.0],"t":349},{"vs":[50.0,112.0,389.12,8.0,2.0],"t":350},{"vs":[40.0,112.0,390.24,8.0,2.0],"t":351},{"vs":[40.0,116.0,391.4,8.0,2.0],"t":352},{"vs":[41.0,120.0,392.6,8.0,2.0],"t":353},{"vs":[43.0,120.0,393.8,8.0,2.0],"t":354},{"vs":[44.0,122.0,395.02,8.0,2.0],"t":355},{"vs":[44.0,124.0,396.26,8.0,2.0],"t":356},{"vs":[44.0,124.0,397.5,8.0,2.0],"t":357},{"vs":[45.0,124.0,398.76,8.0,2.0],"t":358},{"vs":[44.0,124.0,400.0,8.0,2.0],"t":359},{"vs":[44.0,124.0,400.0,8.0,2.0],"t":360},{"vs":[44.0,124.0,400.0,8.0,2.0],"t":360}],"hr":[{"hr":-1,"t":1},{"hr":113,"t":199},{"hr":112,"t":203},{"hr":-1,"t":210},{"hr":112,"t":211},{"hr":113,"t":213},{"hr":114,"t":217},{"hr":113,"t":219},{"hr":112,"t":220},{"hr":111,"t":221},{"hr":110,"t":223},{"hr":109,"t":224},{"hr":108,"t":230},{"hr":110,"t":246},{"hr":112,"t":247},{"hr":115,"t":248},{"hr":116,"t":249},{"hr":117,"t":251},{"hr":118,"t":252},{"hr":-1,"t":258},{"hr":118,"t":259},{"hr":119,"t":260},{"hr":120,"t":264},{"hr":122,"t":266},{"hr":123,"t":268},{"hr":124,"t":269},{"hr":125,"t":270},{"hr":126,"t":273},{"hr":127,"t":276},{"hr":128,"t":277},{"hr":129,"t":278},{"hr":130,"t":279},{"hr":131,"t":280},{"hr":132,"t":282},{"hr":134,"t":283},{"hr":135,"t":284},{"hr":136,"t":288},{"hr":134,"t":290},{"hr":135,"t":293},{"hr":136,"t":294},{"hr":137,"t":295},{"hr":138,"t":299},{"hr":-1,"t":301},{"hr":138,"t":303},{"hr":137,"t":313},{"hr":136,"t":319},{"hr":137,"t":320},{"hr":136,"t":327},{"hr":135,"t":329},{"hr":136,"t":336},{"hr":137,"t":339},{"hr":136,"t":344},{"hr":135,"t":347},{"hr":136,"t":351},{"hr":135,"t":354},{"hr":136,"t":357},{"hr":-1,"t":360}],"hrZones":[{"secondsInZone":16.0,"name":"Very light","color":"#0085BA","upperBound":108.0,"lowerBound":90.0},{"secondsInZone":59.0,"name":"Light","color":"#26DD70","upperBound":126.0,"lowerBound":109.0},{"secondsInZone":82.0,"name":"Moderate","color":"#FFDD00","upperBound":144.0,"lowerBound":127.0},{"secondsInZone":0.0,"name":"Hard","color":"#FC8F00","upperBound":162.0,"lowerBound":145.0},{"secondsInZone":0.0,"name":"Very hard","color":"#CE2929","upperBound":180.0,"lowerBound":163.0}]},"equipmentType":"Synchro","cardioLogId":"65fb2369c82917cd124b4f0f","favorite":0,"name":"Synchro 9000 Excite LiveR: Quick Start","date":"3/20/2024","target":"Duration","nEser":204,"nAttr":1113,"physicalActivityId":"75b438e7-bfa1-4e3a-b18f-1191b3a2ad37","physicalActivityName":"Synchro 9000 Excite LiveR: Quick Start","data":[{"property":"Duration","name":"Duration","value":"06:00","uM":"min","rawValue":6.0},{"property":"HDistance","name":"Distance","value":"0.4","uM":"km","rawValue":0.4},{"property":"Move","name":"MOVEs","value":"88","uM":"MOVEs","rawValue":88.0}]},"token":"MjAyNDAzMjExODM0MTV8MDNhNmNmOWZhOTFmNGMxMTk2NmVmNjBmMzAyYjJkODN8ZWMxZDM4ZDdkMzU5NDhkMGE2MGNkOGMwYjhmYjlkZjl8N3xXLiBFdXJvcGUgU3RhbmRhcmQgVGltZXxlbi1VU3xhZjQzMjE2OTA3Y2Q0OGJhOWVkMTczY2Q5NzExODg3Nnx8fHwxfDF8MHwxfHx8MHwyMjUwfDB8Y29tLm15d2VsbG5lc3M1.CB6D206933582E813BC4D0DAB9E68A9F63DB5E130B69A585F6A0DFFAA9DA22477D4385161B843FB763D1DC2D390FB5D0537F6C3C18360A17C05A635C8046CF7E","version":"1.1.166.25323","expireIn":3600}

**Comment by m3dc85** [comment]
and got this from the chrome dev tools:

wellness2tcx_cljs.js:544 Uncaught Error: Assert failed: (= (count date-string) 10)
    at Zh (wellness2tcx_cljs.js:544:114)
    at li (wellness2tcx_cljs.js:555:204)
    at wellness2tcx_cljs.js:616:205
    at Object.mf (wellness2tcx_cljs.js:118:291)
    at Object.invokeGuardedCallback (wellness2tcx_cljs.js:118:489)
    at Object.invokeGuardedCallbackAndCatchFirstError (wellness2tcx_cljs.js:119:93)
    at Ic (wellness2tcx_cljs.js:50:339)
    at ke (wellness2tcx_cljs.js:121:215)
    at Be (wellness2tcx_cljs.js:121:378)
    at X (wellness2tcx_cljs.js:51:124)

**Comment by m3dc85** [comment]
Found the problem, the date from the export is "date":"3/20/2024" and should be YYYY-mm-dd. Then runs ok
